name: Check for New Reddit Posts and Add to Orbit
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subreddit:
          - javascript
          - vuejs
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npx @orbit-love/reddit --posts --comments --hours=1 --subreddit "${{ matrix.subreddit }}"
        name: 'Get Posts & Add to Orbit'
        env:
          REDDIT_CLIENT_ID: ${{ secrets.G3qRCzLJL4cUXPONhjyYtw}}
          REDDIT_CLIENT_SECRET: ${{ secrets.vTkj94DXUJJcU-Y6hbddu1T_-ptJbQ}}
          REDDIT_USERNAME: ${{ secrets.gxjansen}}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD}}
          ORBIT_API_KEY: ${{ secrets.obu_C5nsoOwhfxcGFGzyTFGbtAIWgYXqmIpd_02QZQYJ}}
          ORBIT_WORKSPACE_ID: ${{ secrets.spryker}}
